#!/usr/bin/env node
// Regenerates path-webapp/js/content-index.js from the current file tree.
// Run locally: node .github/scripts/generate-index.js
// Also runs automatically in the GitHub Actions deploy workflow.

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '../..');
const OUTPUT = path.join(REPO_ROOT, 'path-webapp/js/content-index.js');

// Keys must match the paths used in path-webapp/js/utils.js
const FOLDERS = [
  'the-path-campaign/adversaries/antagonists',
  'the-path-campaign/adversaries/beasts',
  'the-path-campaign/adversaries/mist',
  'the-path-campaign/adversaries/spider-queen',
  'the-path-campaign/adversaries/crystal-plague',
  'the-path-campaign/adversaries/siege',
  'the-path-campaign/mechanics/village-siege/adversaries',
  'the-path-campaign/locations/path-locations/surface-locations',
  'the-path-campaign/locations/path-locations/underground-locations',
  'the-path-campaign/locations/village-in-the-mist',
  'the-path-campaign/example-path/path-library',
];

const index = {};
for (const folder of FOLDERS) {
  const key = `../${folder}/`;
  const abs = path.join(REPO_ROOT, folder);
  let files = [];
  if (fs.existsSync(abs)) {
    files = fs.readdirSync(abs).filter(f => f.endsWith('.yaml')).sort();
  }
  index[key] = files;
}

// Auto-discover factions: scan lore/factions/ for subdirectories containing faction-details.yaml
const FACTIONS_ROOT = 'the-path-campaign/lore/factions';
const factionsAbs = path.join(REPO_ROOT, FACTIONS_ROOT);
const factions = {};
if (fs.existsSync(factionsAbs)) {
  const factionDirs = fs.readdirSync(factionsAbs, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort();

  for (const factionId of factionDirs) {
    const factionPath = path.join(factionsAbs, factionId);
    const detailsFile = path.join(factionPath, 'faction-details.yaml');
    if (!fs.existsSync(detailsFile)) continue;

    const npcsPath = path.join(factionPath, 'npcs');
    const npcs = fs.existsSync(npcsPath)
      ? fs.readdirSync(npcsPath).filter(f => f.endsWith('.yaml')).sort()
      : [];

    factions[factionId] = {
      details: 'faction-details.yaml',
      npcs,
    };
  }
}
index['__factions__'] = factions;

const lines = [
  '// Auto-generated by .github/scripts/generate-index.js — do not edit manually.',
  '// Run: node .github/scripts/generate-index.js',
  'const CONTENT_INDEX = ' + JSON.stringify(index, null, 2) + ';',
];

fs.writeFileSync(OUTPUT, lines.join('\n') + '\n');
console.log(`Written: ${OUTPUT}`);
for (const [k, v] of Object.entries(index)) {
  if (k === '__factions__') {
    const count = Object.keys(v).length;
    console.log(`  factions: ${count} discovered`);
    for (const [id, data] of Object.entries(v)) {
      console.log(`    ${id}: ${data.npcs.length} npcs`);
    }
  } else {
    console.log(`  ${k}: ${v.length} files`);
  }
}
