// Auto-generated by .github/scripts/generate-index.js — do not edit manually.
// Run: node .github/scripts/generate-index.js
const CONTENT_INDEX = {
  "../the-path-campaign/adversaries/antagonists/": [
    "archon-of-mercy.yaml"
  ],
  "../the-path-campaign/adversaries/beasts/": [
    "bff-big-frog.yaml",
    "blood-fern-predator.yaml",
    "eeligator.yaml"
  ],
  "../the-path-campaign/adversaries/mist/": [
    "mist-crab.yaml",
    "mist-octopus.yaml",
    "mist-stalker.yaml",
    "mist-thrower.yaml",
    "mist-walker.yaml",
    "mist-wraith-leader.yaml",
    "void-pearl-monk.yaml"
  ],
  "../the-path-campaign/adversaries/spider-queen/": [
    "giant-spider-guardian.yaml",
    "spider-emissary.yaml",
    "spider-minion.yaml",
    "spider-queen.yaml",
    "spider-swarm.yaml"
  ],
  "../the-path-campaign/adversaries/crystal-plague/": [
    "creature-of-the-cellar.yaml",
    "crystal-fused-guard.yaml",
    "crystal-golem.yaml",
    "crystal-zombie.yaml",
    "crystalline-charger.yaml",
    "the-warden.yaml",
    "trap-crystal.yaml"
  ],
  "../the-path-campaign/adversaries/siege/": [
    "giant-cloud-drifter.yaml",
    "mist-anchor.yaml",
    "pale-shell-drifter-leviathan.yaml"
  ],
  "../the-path-campaign/mechanics/village-siege/adversaries/": [],
  "../the-path-campaign/adversaries/the-croak/": [
    "croak-jumper.yaml",
    "croak-salamander.yaml",
    "croak-swimmer.yaml"
  ],
  "../the-path-campaign/locations/path-locations/surface-locations/": [
    "ancient-crossing.yaml",
    "barnacle-gardens.yaml",
    "bells-edge.yaml",
    "blood-fern-valley.yaml",
    "burnt-clearing.yaml",
    "devils-rock.yaml",
    "forest-refuge.yaml",
    "hanging-gardens.yaml",
    "highland-circle.yaml",
    "highland-watch.yaml",
    "hollow-woods.yaml",
    "lost-flame.yaml",
    "mantaray-tree.yaml",
    "misty-waters.yaml",
    "monastery.yaml",
    "overgrown-temple.yaml",
    "redcloth-pass.yaml",
    "sacred-mountain-pass.yaml",
    "silken-spire.yaml",
    "stone-works.yaml",
    "the-giant-walls.yaml",
    "the-reeds.yaml",
    "unstable-mist.yaml",
    "verdant-crossing.yaml",
    "windswept-grasslands.yaml"
  ],
  "../the-path-campaign/locations/path-locations/underground-locations/": [
    "black-beach.yaml",
    "black-falls.yaml",
    "brood-throne.yaml",
    "crystal-defense-line.yaml",
    "deep-station.yaml",
    "flooded-network.yaml",
    "fungal-depths.yaml",
    "geothermal-caverns.yaml",
    "mining-complex.yaml",
    "needle-tunnels.yaml",
    "outer-mine-line.yaml",
    "red-cellar.yaml",
    "reed-marsh-caverns.yaml",
    "sacred-underground.yaml",
    "sanctum-line.yaml"
  ],
  "../the-path-campaign/locations/path-locations/starfall-city/": [
    "council-hall.yaml",
    "craftsmens-ward.yaml",
    "mechanics-workshop.yaml",
    "old-gate.yaml",
    "riot-market.yaml",
    "sanctuary-keep.yaml",
    "scaffold-square.yaml",
    "sealed-district.yaml",
    "university-burning-fields.yaml"
  ],
  "../the-path-campaign/locations/village-in-the-mist/": [
    "community-hearth-card.yaml",
    "flame-gatherers-lodge-card.yaml",
    "forge-card.yaml",
    "sacred-flame-sanctuary-card.yaml",
    "supply-cache-card.yaml",
    "underground-access-card.yaml"
  ],
  "../the-path-campaign/example-path/path-library/": [
    "clan-extension.yaml",
    "cliff-road.yaml",
    "close-encounters.yaml",
    "deep-station-access.yaml",
    "highland-run.yaml",
    "hollow-cross.yaml",
    "initial-path.yaml",
    "lake-crossing.yaml",
    "monastery-march.yaml",
    "needle-descent.yaml",
    "plague-march.yaml"
  ],
  "__factions__": {
    "archon-of-mercy": {
      "details": "faction-details.yaml",
      "npcs": [
        "archon-of-mercy.yaml",
        "the-bound-raven.yaml"
      ]
    },
    "brass-mechanicorum": {
      "details": "faction-details.yaml",
      "npcs": [
        "copass.yaml"
      ]
    },
    "copper-rust-clan": {
      "details": "faction-details.yaml",
      "npcs": [
        "hund.yaml"
      ]
    },
    "fire-born": {
      "details": "faction-details.yaml",
      "npcs": []
    },
    "mist-born": {
      "details": "faction-details.yaml",
      "npcs": []
    },
    "rootbound": {
      "details": "faction-details.yaml",
      "npcs": [
        "naki.yaml",
        "the-watcher.yaml"
      ]
    },
    "spider-colony": {
      "details": "faction-details.yaml",
      "npcs": [
        "spider-emissary.yaml",
        "spider-queen.yaml"
      ]
    },
    "the-croak": {
      "details": "faction-details.yaml",
      "npcs": [
        "croa.yaml"
      ]
    },
    "village-in-the-mist": {
      "details": "faction-details.yaml",
      "npcs": [
        "brenner.yaml",
        "donatello.yaml",
        "nix.yaml"
      ]
    }
  }
};
